--<< English Localization >>--
if GetLocale()=="enUS"
or GetLocale()=="enGB" then

TITAN_CLASSTRACKER_MENU_TEXT="Class Tracker";
TITAN_CLASSTRACKER_BUTTON_TEXT="o";
TITAN_CLASSTRACKER_TOOLTIP_NA="Nothing to track";
TITAN_CLASSTRACKER_TOOLTIP_CLICK = "Right-click for options";
TITAN_CLASSTRACKER_TOOLTIP = "Tracking";
TITAN_CLASSTRACKER_BUTTON_TINY="CT:";
TITAN_CT_MENU_SHOW_TITLE = "Show Class Title";
TITAN_CT_MENU_SHOW_TRACKER = "Show Tracker";

TITAN_WARRIOR_TITLE = "Warrior Tracker";
TITAN_HUNTER_TITLE = "Hunter Tracker";

TITAN_WARLOCK_TITLE = "Warlock Tracker";
TITAN_WARLOCK_BUTTON_LABEL="SoulShards: ";
TITAN_WARLOCK_BUTTON_TEXTSHARDS="%s";
TITAN_WARLOCK_TOOLTIP_SHARDS = "Soul Shards: %s";
TITAN_WARLOCK_TOOLTIP_HEALTH = "Healthstone: %s";
TITAN_WARLOCK_TOOLTIP_SOUL = "Soulstone: %s";
TITAN_WARLOCK_TOOLTIP_SPELL = "Spellstone: %s";
TITAN_WARLOCK_TOOLTIP_FIRE = "Firestone: %s";

TITAN_SHAMAN_TITLE = "Shaman Tracker";
TITAN_SHAMAN_BUTTON_LABEL="Ankhs: ";
TITAN_SHAMAN_BUTTON_TEXTANKHS="%s";
TITAN_SHAMAN_TOOLTIP_ANKHS = "Ankhs: %s";
TITAN_SHAMAN_TOOLTIP_SCALES = "Shiny Fish Scales: %s";
TITAN_SHAMAN_TOOLTIP_OIL = "Fish Oil: %s";

TITAN_MAGE_TITLE = "Mage Tracker";
TITAN_MAGE_BUTTON_LABELTELE="TeleRunes: ";
TITAN_MAGE_BUTTON_LABELPORTAL="PortalRunes: ";
TITAN_MAGE_BUTTON_TEXTTELE="%s";
TITAN_MAGE_BUTTON_TEXTPORTAL="%s";
TITAN_MAGE_TOOLTIP_TELE = "Teleport Runes: %s";
TITAN_MAGE_TOOLTIP_PORTAL = "Portal Runes: %s";
TITAN_MAGE_TOOLTIP_ARCANE = "Arcane Powder: %s";
TITAN_MAGE_TOOLTIP_FEATHER = "Light Feather: %s";

TITAN_ROGUE_TITLE = "Rogue Tracker";
TITAN_ROGUE_BUTTON_LABELFLASH="Flash: ";
TITAN_ROGUE_BUTTON_LABELBLIND="Blinding: ";
TITAN_ROGUE_BUTTON_LABELPOISONS="Poisons: ";
TITAN_ROGUE_BUTTON_TEXTFLASH="%s";
TITAN_ROGUE_BUTTON_TEXTBLIND="%s";
TITAN_ROGUE_BUTTON_TEXTPOISONS="%s";
TITAN_ROGUE_TOOLTIP_FLASH = "Flash Powder: %s";
TITAN_ROGUE_TOOLTIP_BLIND = "Blinding Powder: %s";
TITAN_ROGUE_TOOLTIP_THISTLE = "Thistle Tea: %s";
TITAN_ROGUE_TOOLTIP_INSTANT = "Instant Poisons: %s";
TITAN_ROGUE_TOOLTIP_DEADLY = "Deadly Poisons: %s";
TITAN_ROGUE_TOOLTIP_CRIPPLING = "Crippling Poisons: %s";
TITAN_ROGUE_TOOLTIP_MINDNUMB = "Mind-numbing Poisons: %s";
TITAN_ROGUE_TOOLTIP_WOUND = "Wound Poisons: %s";

TITAN_DRUID_TITLE = "Druid Tracker";
TITAN_DRUID_BUTTON_LABELSEEDS="Seeds: ";
TITAN_DRUID_BUTTON_LABELWILD="Wilds: ";
TITAN_DRUID_BUTTON_TEXTSEEDS="%s";
TITAN_DRUID_BUTTON_TEXTWILD="%s";
TITAN_DRUID_TOOLTIP_MSEED = "Maple Seed: %s";
TITAN_DRUID_TOOLTIP_SSEED = "Stranglethorn Seed: %s";
TITAN_DRUID_TOOLTIP_ASEED = "Ashwood Seed: %s";
TITAN_DRUID_TOOLTIP_HSEED = "Hornbeam Seed: %s";
TITAN_DRUID_TOOLTIP_ISEED = "Ironwood Seed: %s";
TITAN_DRUID_TOOLTIP_BERRIES = "Wild Berries: %s";
TITAN_DRUID_TOOLTIP_THORNROOT = "Wild Thornroot: %s";

TITAN_PRIEST_TITLE = "Priest Tracker";
TITAN_PRIEST_BUTTON_LABELFEATHERS="Feathers: ";
TITAN_PRIEST_BUTTON_LABELCANDLES="Candles: ";
TITAN_PRIEST_BUTTON_TEXTFEATHER="%s";
TITAN_PRIEST_BUTTON_TEXTCANDLES="%s";
TITAN_PRIEST_TOOLTIP_FEATHER = "Light Feather: %s";
TITAN_PRIEST_TOOLTIP_HCANDLE = "Holy Candle: %s";
TITAN_PRIEST_TOOLTIP_SCANDLE = "Sacred Candle: %s";

TITAN_PALADIN_TITLE = "Paladin Tracker";
TITAN_PALADIN_BUTTON_LABELSYMBOL="Symbol: ";
TITAN_PALADIN_BUTTON_TEXTSYMBOL="%s";
TITAN_PALADIN_TOOLTIP_SYMBOL = "Symbol of Divinity: %s";

return
end

--<< French Localization >>--
if GetLocale()=="frFR" then

TITAN_CLASSTRACKER_MENU_TEXT="Class Tracker";
TITAN_CLASSTRACKER_BUTTON_TEXT="o";
TITAN_CLASSTRACKER_TOOLTIP_NA="Nothing to track";
TITAN_CLASSTRACKER_TOOLTIP_CLICK = "Right-click for options";
TITAN_CLASSTRACKER_TOOLTIP = "Tracking";
TITAN_CLASSTRACKER_BUTTON_TINY="CT:";
TITAN_CT_MENU_SHOW_TITLE = "Show Class Title";
TITAN_CT_MENU_SHOW_TRACKER = "Show Tracker";

TITAN_WARRIOR_TITLE = "Warrior Tracker";
TITAN_HUNTER_TITLE = "Hunter Tracker";

TITAN_WARLOCK_TITLE = "Warlock Tracker";
TITAN_WARLOCK_BUTTON_LABEL="SoulShards: ";
TITAN_WARLOCK_BUTTON_TEXTSHARDS="%s";
TITAN_WARLOCK_TOOLTIP_SHARDS = "Soul Shards: %s";
TITAN_WARLOCK_TOOLTIP_HEALTH = "Healthstone: %s";
TITAN_WARLOCK_TOOLTIP_SOUL = "Soulstone: %s";
TITAN_WARLOCK_TOOLTIP_SPELL = "Spellstone: %s";
TITAN_WARLOCK_TOOLTIP_FIRE = "Firestone: %s";

TITAN_SHAMAN_TITLE = "Shaman Tracker";
TITAN_SHAMAN_BUTTON_LABEL="Ankhs: ";
TITAN_SHAMAN_BUTTON_TEXTANKHS="%s";
TITAN_SHAMAN_TOOLTIP_ANKHS = "Ankhs: %s";
TITAN_SHAMAN_TOOLTIP_SCALES = "Shiny Fish Scales: %s";
TITAN_SHAMAN_TOOLTIP_OIL = "Fish Oil: %s";

TITAN_MAGE_TITLE = "Mage Tracker";
TITAN_MAGE_BUTTON_LABELTELE="TeleRunes: ";
TITAN_MAGE_BUTTON_LABELPORTAL="PortalRunes: ";
TITAN_MAGE_BUTTON_TEXTTELE="%s";
TITAN_MAGE_BUTTON_TEXTPORTAL="%s";
TITAN_MAGE_TOOLTIP_TELE = "Teleport Runes: %s";
TITAN_MAGE_TOOLTIP_PORTAL = "Portal Runes: %s";
TITAN_MAGE_TOOLTIP_ARCANE = "Arcane Powder: %s";
TITAN_MAGE_TOOLTIP_FEATHER = "Light Feather: %s";

TITAN_ROGUE_TITLE = "Rogue Tracker";
TITAN_ROGUE_BUTTON_LABELFLASH="Flash: ";
TITAN_ROGUE_BUTTON_LABELBLIND="Blinding: ";
TITAN_ROGUE_BUTTON_LABELPOISONS="Poisons: ";
TITAN_ROGUE_BUTTON_TEXTFLASH="%s";
TITAN_ROGUE_BUTTON_TEXTBLIND="%s";
TITAN_ROGUE_BUTTON_TEXTPOISONS="%s";
TITAN_ROGUE_TOOLTIP_FLASH = "Flash Powder: %s";
TITAN_ROGUE_TOOLTIP_BLIND = "Blinding Powder: %s";
TITAN_ROGUE_TOOLTIP_THISTLE = "Thistle Tea: %s";
TITAN_ROGUE_TOOLTIP_INSTANT = "Instant Poisons: %s";
TITAN_ROGUE_TOOLTIP_DEADLY = "Deadly Poisons: %s";
TITAN_ROGUE_TOOLTIP_CRIPPLING = "Crippling Poisons: %s";
TITAN_ROGUE_TOOLTIP_MINDNUMB = "Mind-numbing Poisons: %s";
TITAN_ROGUE_TOOLTIP_WOUND = "Wound Poisons: %s";

TITAN_DRUID_TITLE = "Druid Tracker";
TITAN_DRUID_BUTTON_LABELSEEDS="Seeds: ";
TITAN_DRUID_BUTTON_LABELWILD="Wilds: ";
TITAN_DRUID_BUTTON_TEXTSEEDS="%s";
TITAN_DRUID_BUTTON_TEXTWILD="%s";
TITAN_DRUID_TOOLTIP_MSEED = "Maple Seed: %s";
TITAN_DRUID_TOOLTIP_SSEED = "Stranglethorn Seed: %s";
TITAN_DRUID_TOOLTIP_ASEED = "Ashwood Seed: %s";
TITAN_DRUID_TOOLTIP_HSEED = "Hornbeam Seed: %s";
TITAN_DRUID_TOOLTIP_ISEED = "Ironwood Seed: %s";
TITAN_DRUID_TOOLTIP_BERRIES = "Wild Berries: %s";
TITAN_DRUID_TOOLTIP_THORNROOT = "Wild Thornroot: %s";

TITAN_PRIEST_TITLE = "Priest Tracker";
TITAN_PRIEST_BUTTON_LABELFEATHERS="Feathers: ";
TITAN_PRIEST_BUTTON_LABELCANDLES="Candles: ";
TITAN_PRIEST_BUTTON_TEXTFEATHER="%s";
TITAN_PRIEST_BUTTON_TEXTCANDLES="%s";
TITAN_PRIEST_TOOLTIP_FEATHER = "Light Feather: %s";
TITAN_PRIEST_TOOLTIP_HCANDLE = "Holy Candle: %s";
TITAN_PRIEST_TOOLTIP_SCANDLE = "Sacred Candle: %s";

TITAN_PALADIN_TITLE = "Paladin Tracker";
TITAN_PALADIN_BUTTON_LABELSYMBOL="Symbol: ";
TITAN_PALADIN_BUTTON_TEXTSYMBOL="%s";
TITAN_PALADIN_TOOLTIP_SYMBOL = "Symbol of Divinity: %s";

return
end

--<< German Localization >>--
if GetLocale()=="deDE" then

TITAN_CLASSTRACKER_MENU_TEXT="Class Tracker";
TITAN_CLASSTRACKER_BUTTON_TEXT="o";
TITAN_CLASSTRACKER_TOOLTIP_NA="Nothing to track";
TITAN_CLASSTRACKER_TOOLTIP_CLICK = "Right-click for options";
TITAN_CLASSTRACKER_TOOLTIP = "Tracking";
TITAN_CLASSTRACKER_BUTTON_TINY="CT:";
TITAN_CT_MENU_SHOW_TITLE = "Show Class Title";
TITAN_CT_MENU_SHOW_TRACKER = "Show Tracker";

TITAN_WARRIOR_TITLE = "Warrior Tracker";
TITAN_HUNTER_TITLE = "Hunter Tracker";

TITAN_WARLOCK_TITLE = "Warlock Tracker";
TITAN_WARLOCK_BUTTON_LABEL="SoulShards: ";
TITAN_WARLOCK_BUTTON_TEXTSHARDS="%s";
TITAN_WARLOCK_TOOLTIP_SHARDS = "Soul Shards: %s";
TITAN_WARLOCK_TOOLTIP_HEALTH = "Healthstone: %s";
TITAN_WARLOCK_TOOLTIP_SOUL = "Soulstone: %s";
TITAN_WARLOCK_TOOLTIP_SPELL = "Spellstone: %s";
TITAN_WARLOCK_TOOLTIP_FIRE = "Firestone: %s";

TITAN_SHAMAN_TITLE = "Shaman Tracker";
TITAN_SHAMAN_BUTTON_LABEL="Ankhs: ";
TITAN_SHAMAN_BUTTON_TEXTANKHS="%s";
TITAN_SHAMAN_TOOLTIP_ANKHS = "Ankhs: %s";
TITAN_SHAMAN_TOOLTIP_SCALES = "Shiny Fish Scales: %s";
TITAN_SHAMAN_TOOLTIP_OIL = "Fish Oil: %s";

TITAN_MAGE_TITLE = "Mage Tracker";
TITAN_MAGE_BUTTON_LABELTELE="TeleRunes: ";
TITAN_MAGE_BUTTON_LABELPORTAL="PortalRunes: ";
TITAN_MAGE_BUTTON_TEXTTELE="%s";
TITAN_MAGE_BUTTON_TEXTPORTAL="%s";
TITAN_MAGE_TOOLTIP_TELE = "Teleport Runes: %s";
TITAN_MAGE_TOOLTIP_PORTAL = "Portal Runes: %s";
TITAN_MAGE_TOOLTIP_ARCANE = "Arcane Powder: %s";
TITAN_MAGE_TOOLTIP_FEATHER = "Light Feather: %s";

TITAN_ROGUE_TITLE = "Rogue Tracker";
TITAN_ROGUE_BUTTON_LABELFLASH="Flash: ";
TITAN_ROGUE_BUTTON_LABELBLIND="Blinding: ";
TITAN_ROGUE_BUTTON_LABELPOISONS="Poisons: ";
TITAN_ROGUE_BUTTON_TEXTFLASH="%s";
TITAN_ROGUE_BUTTON_TEXTBLIND="%s";
TITAN_ROGUE_BUTTON_TEXTPOISONS="%s";
TITAN_ROGUE_TOOLTIP_FLASH = "Flash Powder: %s";
TITAN_ROGUE_TOOLTIP_BLIND = "Blinding Powder: %s";
TITAN_ROGUE_TOOLTIP_THISTLE = "Thistle Tea: %s";
TITAN_ROGUE_TOOLTIP_INSTANT = "Instant Poisons: %s";
TITAN_ROGUE_TOOLTIP_DEADLY = "Deadly Poisons: %s";
TITAN_ROGUE_TOOLTIP_CRIPPLING = "Crippling Poisons: %s";
TITAN_ROGUE_TOOLTIP_MINDNUMB = "Mind-numbing Poisons: %s";
TITAN_ROGUE_TOOLTIP_WOUND = "Wound Poisons: %s";

TITAN_DRUID_TITLE = "Druid Tracker";
TITAN_DRUID_BUTTON_LABELSEEDS="Seeds: ";
TITAN_DRUID_BUTTON_LABELWILD="Wilds: ";
TITAN_DRUID_BUTTON_TEXTSEEDS="%s";
TITAN_DRUID_BUTTON_TEXTWILD="%s";
TITAN_DRUID_TOOLTIP_MSEED = "Maple Seed: %s";
TITAN_DRUID_TOOLTIP_SSEED = "Stranglethorn Seed: %s";
TITAN_DRUID_TOOLTIP_ASEED = "Ashwood Seed: %s";
TITAN_DRUID_TOOLTIP_HSEED = "Hornbeam Seed: %s";
TITAN_DRUID_TOOLTIP_ISEED = "Ironwood Seed: %s";
TITAN_DRUID_TOOLTIP_BERRIES = "Wild Berries: %s";
TITAN_DRUID_TOOLTIP_THORNROOT = "Wild Thornroot: %s";

TITAN_PRIEST_TITLE = "Priest Tracker";
TITAN_PRIEST_BUTTON_LABELFEATHERS="Feathers: ";
TITAN_PRIEST_BUTTON_LABELCANDLES="Candles: ";
TITAN_PRIEST_BUTTON_TEXTFEATHER="%s";
TITAN_PRIEST_BUTTON_TEXTCANDLES="%s";
TITAN_PRIEST_TOOLTIP_FEATHER = "Light Feather: %s";
TITAN_PRIEST_TOOLTIP_HCANDLE = "Holy Candle: %s";
TITAN_PRIEST_TOOLTIP_SCANDLE = "Sacred Candle: %s";

TITAN_PALADIN_TITLE = "Paladin Tracker";
TITAN_PALADIN_BUTTON_LABELSYMBOL="Symbol: ";
TITAN_PALADIN_BUTTON_TEXTSYMBOL="%s";
TITAN_PALADIN_TOOLTIP_SYMBOL = "Symbol of Divinity: %s";

return
end

---------chinese   Localization----------

if GetLocale()=="zhCN" then

TITAN_CLASSTRACKER_MENU_TEXT="职业物品跟踪器";
TITAN_CLASSTRACKER_BUTTON_TEXT="o";
TITAN_CLASSTRACKER_TOOLTIP_NA="没有跟踪对象";
TITAN_CLASSTRACKER_TOOLTIP_CLICK = "右键点击打开选项";
TITAN_CLASSTRACKER_TOOLTIP = "跟踪";
TITAN_CLASSTRACKER_BUTTON_TINY="CT:";
TITAN_CT_MENU_SHOW_TITLE = "显示职业名称";
TITAN_CT_MENU_SHOW_TRACKER = "显示跟踪器";

TITAN_WARRIOR_TITLE = "战士跟踪器";
TITAN_HUNTER_TITLE = "猎人跟踪器";

TITAN_WARLOCK_TITLE = "术士跟踪器";
TITAN_WARLOCK_BUTTON_LABEL="灵魂碎片: ";
TITAN_WARLOCK_BUTTON_TEXTSHARDS="%s";
TITAN_WARLOCK_TOOLTIP_SHARDS = "灵魂碎片: %s";
TITAN_WARLOCK_TOOLTIP_HEALTH = "治疗石: %s";
TITAN_WARLOCK_TOOLTIP_SOUL = "灵魂石: %s";
TITAN_WARLOCK_TOOLTIP_SPELL = "法术石: %s";
TITAN_WARLOCK_TOOLTIP_FIRE = "火焰石: %s";

TITAN_SHAMAN_TITLE = "萨满祭司跟踪器";
TITAN_SHAMAN_BUTTON_LABEL="十字章: ";
TITAN_SHAMAN_BUTTON_TEXTANKHS="%s";
TITAN_SHAMAN_TOOLTIP_ANKHS = "十字章: %s";
TITAN_SHAMAN_TOOLTIP_SCALES = "闪亮的鱼鳞: %s";
TITAN_SHAMAN_TOOLTIP_OIL = "鱼油: %s";

TITAN_MAGE_TITLE = "法师跟踪器";
TITAN_MAGE_BUTTON_LABELTELE="传送符文: ";
TITAN_MAGE_BUTTON_LABELPORTAL="传送门符文: ";
TITAN_MAGE_BUTTON_TEXTTELE="%s";
TITAN_MAGE_BUTTON_TEXTPORTAL="%s";
TITAN_MAGE_TOOLTIP_TELE = "传送符文: %s";
TITAN_MAGE_TOOLTIP_PORTAL = "传送门符文: %s";
TITAN_MAGE_TOOLTIP_ARCANE = "魔粉: %s";
TITAN_MAGE_TOOLTIP_FEATHER = "轻羽毛: %s";

TITAN_ROGUE_TITLE = "盗贼跟踪器";
TITAN_ROGUE_BUTTON_LABELFLASH="闪光粉: ";
TITAN_ROGUE_BUTTON_LABELBLIND="致盲粉: ";
TITAN_ROGUE_BUTTON_LABELPOISONS="毒药: ";
TITAN_ROGUE_BUTTON_TEXTFLASH="%s";
TITAN_ROGUE_BUTTON_TEXTBLIND="%s";
TITAN_ROGUE_BUTTON_TEXTPOISONS="%s";
TITAN_ROGUE_TOOLTIP_FLASH = "闪光粉: %s";
TITAN_ROGUE_TOOLTIP_BLIND = "致盲粉: %s";
TITAN_ROGUE_TOOLTIP_THISTLE = "菊花茶: %s";
TITAN_ROGUE_TOOLTIP_INSTANT = "速效毒药: %s";
TITAN_ROGUE_TOOLTIP_DEADLY = "致命毒药: %s";
TITAN_ROGUE_TOOLTIP_CRIPPLING = "致残毒药: %s";
TITAN_ROGUE_TOOLTIP_MINDNUMB = "麻痹毒药: %s";
TITAN_ROGUE_TOOLTIP_WOUND = "致伤毒药: %s";

TITAN_DRUID_TITLE = "德鲁伊跟踪器";
TITAN_DRUID_BUTTON_LABELSEEDS="种子: ";
TITAN_DRUID_BUTTON_LABELWILD="野性: ";
TITAN_DRUID_BUTTON_TEXTSEEDS="%s";
TITAN_DRUID_BUTTON_TEXTWILD="%s";
TITAN_DRUID_TOOLTIP_MSEED = "枫树种子: %s";
TITAN_DRUID_TOOLTIP_SSEED = "荆棘种子: %s";
TITAN_DRUID_TOOLTIP_ASEED = "灰木种子: %s";
TITAN_DRUID_TOOLTIP_HSEED = "角树种子: %s";
TITAN_DRUID_TOOLTIP_ISEED = "铁木种子: %s";
TITAN_DRUID_TOOLTIP_BERRIES = "野生漿果: %s";
TITAN_DRUID_TOOLTIP_THORNROOT = "野生棘根草: %s";

TITAN_PRIEST_TITLE = "牧师跟踪器";
TITAN_PRIEST_BUTTON_LABELFEATHERS="轻羽毛: ";
TITAN_PRIEST_BUTTON_LABELCANDLES="轻羽毛: ";
TITAN_PRIEST_BUTTON_TEXTFEATHER="%s";
TITAN_PRIEST_BUTTON_TEXTCANDLES="%s";
TITAN_PRIEST_TOOLTIP_FEATHER = "轻羽毛: %s";
TITAN_PRIEST_TOOLTIP_HCANDLE = "圣洁蜡烛: %s";
TITAN_PRIEST_TOOLTIP_SCANDLE = "神圣蜡烛: %s";

TITAN_PALADIN_TITLE = "圣骑士跟踪器";
TITAN_PALADIN_BUTTON_LABELSYMBOL="神圣符印: ";
TITAN_PALADIN_BUTTON_TEXTSYMBOL="%s";
TITAN_PALADIN_TOOLTIP_SYMBOL = "神圣符印: %s";

return
end