function TitanLocalizeCN()
	TITAN_DEBUG = "<Titan>";
	TITAN_INFO = "<Titan>"
	
	TITAN_NA = "N/A";
	TITAN_SECONDS = "秒";
	TITAN_MINUTES = "分";
	TITAN_HOURS = "小时";
	TITAN_DAYS = "天";
	TITAN_SECONDS_ABBR = "秒";
	TITAN_MINUTES_ABBR = "分";
	TITAN_HOURS_ABBR = "时";
	TITAN_DAYS_ABBR = "天";
	TITAN_MILLISECOND = "毫秒";
	TITAN_KILOBYTES_PER_SECOND = "KB/s";
	TITAN_KILOBITS_PER_SECOND = "kbps"
	TITAN_MEGABYTE = "MB";
	
	TITAN_MOVABLE_TOOLTIP = "按住鼠标来拖动";

	TITAN_PANEL_ERROR_DUP_PLUGIN = " 似乎注册了两次，这会导致泰坦面板功能错误，请修正这个问题"
	
	TITAN_PANEL = "泰坦面板";
	TITAN_PANEL_MENU_TITLE = "泰坦面板菜单";
	TITAN_PANEL_MENU_HIDE = "隐藏";
	TITAN_PANEL_MENU_CUSTOMIZE = "自定义";
	TITAN_PANEL_MENU_SHOW_COLORED_TEXT = "使用颜色显示";
	TITAN_PANEL_MENU_SHOW_ICON = "显示图标";
	TITAN_PANEL_MENU_SHOW_LABEL_TEXT = "显示标签文字";
	TITAN_PANEL_MENU_AUTOHIDE = "自动隐藏泰坦面板";
	TITAN_PANEL_MENU_BGMINIMAP = "战场小地图";
	TITAN_PANEL_MENU_CENTER_TEXT = "文字居中";
	TITAN_PANEL_MENU_DISPLAY_ONTOP = "显示在屏幕顶端";
	TITAN_PANEL_MENU_DISPLAY_BOTH = "同时显示在屏幕底部";
	TITAN_PANEL_MENU_DISABLE_PUSH = "禁止屏幕调节";
	TITAN_PANEL_MENU_BUILTINS = "泰坦内置插件";
	TITAN_PANEL_MENU_LEFT_SIDE = "左侧";
	TITAN_PANEL_MENU_RIGHT_SIDE = "右侧";
	TITAN_PANEL_MENU_LOAD_SETTINGS = "读取设置";
	TITAN_PANEL_MENU_DOUBLE_BAR = "双状态条";
	TITAN_PANEL_MENU_OPTIONS = "设置";
	TITAN_PANEL_MENU_PLUGINS = "插件";
	TITAN_PANEL_MENU_VERSION_SHOWN = "显示插件版本";
	TITAN_PANEL_MENU_DISBALE_FONT = "禁用界面字体缩放";
	TITAN_PANEL_MENU_CATEGORIES = {"常规插件","战斗插件","信息插件","界面插件","专业插件"}
	TITAN_PANEL_MENU_TOOLTIPS_SHOWN = "显示提示信息";
	TITAN_PANEL_MENU_CASTINGBAR = "移动施法条";
	
	TITAN_AUTOHIDE_TOOLTIP = "切换泰坦面板窗口自动隐藏状态";
	TITAN_AUTOHIDE_MENU_TEXT = "自动隐藏";
	
	TITAN_AMMO_FORMAT = "%d";
	TITAN_AMMO_BUTTON_LABEL_AMMO = "弹药:";
	TITAN_AMMO_BUTTON_LABEL_THROWN = "投掷:";
	TITAN_AMMO_BUTTON_LABEL_AMMO_THROWN = "弹药/投掷:";
	TITAN_AMMO_TOOLTIP = "已装备的弹药/投掷武器数量";
	TITAN_AMMO_MENU_TEXT = "弹药/投掷";
	TITAN_AMMO_THROWN_KEYWORD = "投掷武器";
	
	TITAN_BAG_FORMAT = "%d/%d";
	TITAN_BAG_BUTTON_LABEL = "背包: ";
	TITAN_BAG_TOOLTIP = "背包状态";
	TITAN_BAG_TOOLTIP_HINTS = "左键单击打开所有包裹.";
	TITAN_BAG_MENU_TEXT = "背包";
	TITAN_BAG_MENU_SHOW_USED_SLOTS = "显示已使用空间";
	TITAN_BAG_MENU_SHOW_AVAILABLE_SLOTS = "显示剩余空间";
	TITAN_BAG_MENU_IGNORE_AMMO_POUCH_SLOTS = "忽略弹药包（箭袋）空间";
	TITAN_BAG_MENU_IGNORE_SHARD_BAGS_SLOTS = "忽略灵魂碎片包裹空间";
	TITAN_BAG_MENU_IGNORE_PROF_BAGS_SLOTS = "忽略专业（草药、附魔）包裹空间";
	TITAN_BAG_SHARD_BAG_NAMES = {"灵魂","布料包"};
	TITAN_BAG_AMMO_POUCH_NAMES = {"弹药", "箭", "弹药包", "炮弹", "飞刀"};
	TITAN_BAG_PROF_BAG_NAMES = {"魔化","附魔袋","草药包","塞纳留斯之袋"};

	TITAN_BGMINIMAP_MENU_TEXT = "战场小地图"
	TITAN_BGMINIMAP_TOOLTIP = "打开/关闭 战场小地图"
	
	TITAN_CLOCK_TOOLTIP = "时钟";
	TITAN_CLOCK_TOOLTIP_VALUE = "当前时差: ";
	TITAN_CLOCK_TOOLTIP_HINT1 = "左键单击调整时差"
	TITAN_CLOCK_TOOLTIP_HINT2 = "和12/24小时模式.";
	TITAN_CLOCK_CONTROL_TOOLTIP = "时差:";
	TITAN_CLOCK_CONTROL_TITLE = "时差";
	TITAN_CLOCK_CONTROL_HIGH = "+12";
	TITAN_CLOCK_CONTROL_LOW = "-12";
	TITAN_CLOCK_CHECKBUTTON = "24小时制";
	TITAN_CLOCK_CHECKBUTTON_TOOLTIP = "切换12/24小时制显示方式";
	TITAN_CLOCK_MENU_TEXT = "时钟";
	TITAN_CLOCK_MENU_DISPLAY_ON_RIGHT_SIDE = "最右侧显示";
	
	TITAN_COORDS_FORMAT = "(%.d, %.d)";
	TITAN_COORDS_BUTTON_LABEL = "位置:";
	TITAN_COORDS_TOOLTIP = "位置信息";
	TITAN_COORDS_TOOLTIP_HINTS_1 = "Shift + 左键单击将当前位置";
	TITAN_COORDS_TOOLTIP_HINTS_2 = "信息加入到聊天输入窗口.";
	TITAN_COORDS_TOOLTIP_ZONE = "区域:";
	TITAN_COORDS_TOOLTIP_SUBZONE = "分区:";
	TITAN_COORDS_TOOLTIP_PVPINFO = "PVP信息:";
	TITAN_COORDS_TOOLTIP_HOMELOCATION = "安家地点";
	TITAN_COORDS_TOOLTIP_INN = "旅馆:";
	TITAN_COORDS_MENU_TEXT = "区域";
	TITAN_COORDS_MENU_SHOW_ZONE_ON_PANEL_TEXT = "显示区域";
	TITAN_COORDS_MENU_SHOW_COORDS_ON_MAP_TEXT = "在地图上显示坐标";
	TITAN_COORDS_MAP_COORDS_TEXT = "%d, %d";
	TITAN_COORDS_MAP_CURSOR_COORDS_TEXT = "鼠标(X,Y): %s";
	TITAN_COORDS_MAP_PLAYER_COORDS_TEXT = "玩家(X,Y): %s";
	
	TITAN_FPS_FORMAT = "%.1f";
	TITAN_FPS_BUTTON_LABEL = "FPS: ";
	TITAN_FPS_MENU_TEXT = "FPS";
	TITAN_FPS_TOOLTIP_CURRENT_FPS = "当前FPS:";
	TITAN_FPS_TOOLTIP_AVG_FPS = "平均FPS:";
	TITAN_FPS_TOOLTIP_MIN_FPS = "最低FPS:";
	TITAN_FPS_TOOLTIP_MAX_FPS = "最高FPS:";
	TITAN_FPS_TOOLTIP = "每秒帧数";
	
	TITAN_HONOR_BUTTON_LABEL_RANK = RANK..": ";
	TITAN_HONOR_BUTTON_LABEL_HK = "HK: ";
	TITAN_HONOR_BUTTON_LABEL_DK = "DK: ";
	TITAN_HONOR_TOOLTIP = "PVP 荣誉信息";
	TITAN_HONOR_MENU_TEXT = "PVP 荣誉";
	
	TITAN_LATENCY_FORMAT = "%d"..TITAN_MILLISECOND;
	TITAN_LATENCY_BANDWIDTH_FORMAT = "%.3f "..TITAN_KILOBYTES_PER_SECOND;
	TITAN_LATENCY_BUTTON_LABEL = "延迟:";
	TITAN_LATENCY_TOOLTIP = "网络状况";
	TITAN_LATENCY_TOOLTIP_LATENCY = "延迟:";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_IN = "接收带宽: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_OUT = "发送带宽: ";
	TITAN_LATENCY_MENU_TEXT = "延迟";
	
	TITAN_LOOTTYPE_BUTTON_LABEL = "分配:";
	TITAN_LOOTTYPE_FREE_FOR_ALL = "自由拾取";
	TITAN_LOOTTYPE_ROUND_ROBIN = "轮流拾取";
	TITAN_LOOTTYPE_MASTER_LOOTER = "队长分配";
	TITAN_LOOTTYPE_GROUP_LOOT = "队伍分配";
	TITAN_LOOTTYPE_NEED_BEFORE_GREED = "需求优先";
	TITAN_LOOTTYPE_TOOLTIP = "分配方式";
	TITAN_LOOTTYPE_MENU_TEXT = "分配方式";
	
	TITAN_MEMORY_FORMAT = "%.3f"..TITAN_MEGABYTE;
	TITAN_MEMORY_RATE_FORMAT = "%.3f"..TITAN_KILOBYTES_PER_SECOND;
	TITAN_MEMORY_BUTTON_LABEL = "内存:";
	TITAN_MEMORY_TOOLTIP = "UI内存使用";
	TITAN_MEMORY_TOOLTIP_CURRENT_MEMORY = "当前内存使用:";
	TITAN_MEMORY_TOOLTIP_INITIAL_MEMORY = "起始内存使用: ";
	TITAN_MEMORY_TOOLTIP_INCREASING_RATE = "内存使用增长率: ";
	TITAN_MEMORY_TOOLTIP_GC_INFO = "内存回收信息: ";
	TITAN_MEMORY_TOOLTIP_GC_THRESHOLD = "内存回收界限: ";
	TITAN_MEMORY_TOOLTIP_TIME_TO_GC = "下次内存回收时间: "
	TITAN_MEMORY_MENU_TEXT = "UI内存使用";
	TITAN_MEMORY_MENU_RESET_SESSION = "重置内存统计数据";
	
	TITAN_MONEY_GOLD = "金";
	TITAN_MONEY_SILVER = "银";
	TITAN_MONEY_COPPER = "铜";
	TITAN_MONEY_FORMAT = "%d"..TITAN_MONEY_GOLD..", %d"..TITAN_MONEY_SILVER..", %d"..TITAN_MONEY_COPPER;
	TITAN_MONEY_MENU_TEXT = "金钱";
	TITAN_MONEY_MENU_RESET_SESSION = "重置金钱统计";
	TITAN_MONEY_TOOLTIP = "显示金钱变化";
	TITAN_MONEY_TOOLTIP_HINTS = "左键单击拿取金钱.";
	TITAN_MONEY_TOOLTIP_CURRENT = "当前: ";
	TITAN_MONEY_TOOLTIP_INITIAL = "初始: ";
	TITAN_MONEY_TOOLTIP_EARNED = "收入: ";
	TITAN_MONEY_TOOLTIP_LOST = "支出: ";
	TITAN_MONEY_TOOLTIP_EARNED_HOUR = "收入/小时: ";
	TITAN_MONEY_TOOLTIP_LOST_HOUR = "支出/小时: ";
	
	TITAN_PERFORMANCE_TOOLTIP = "性能";
	TITAN_PERFORMANCE_MENU_TEXT = "性能";
	TITAN_PERFORMANCE_MENU_SHOW_FPS = "显示 FPS";
	TITAN_PERFORMANCE_MENU_SHOW_LATENCY = "显示网络延迟";
	TITAN_PERFORMANCE_MENU_SHOW_MEMORY = "显示内存使用";

	TITAN_RIDER_HINT = "当前骑乘状态: ";
	TITAN_RIDER_OPTIONS_SHOWSTATE = "显示玩家状态";
	TITAN_RIDER_OPTIONS_EQUIP = "装备";
	TITAN_RIDER_STATES = {"步行", "骑乘", "飞行", "变羊"};
	TITAN_RIDER_ITEMS = 3;
	TITAN_RIDER_ITEM_NAMES = {nil,"Carrot on a Stick",nil};
	TITAN_RIDER_ITEM_DESCS = {"Mithril Spurs",nil,"Minor Mount Speed Increase"};
	TITAN_RIDER_ITEM_SLOTS = {"FeetSlot","Trinket0Slot","HandsSlot"}

	TITAN_TRANS_TOOLTIP = "调整面板透明度";
	TITAN_TRANS_TOOLTIP_VALUE = "当前面板透明度: ";
	TITAN_TRANS_TOOLTIP_HINT1 = "左键单击调整";
	TITAN_TRANS_TOOLTIP_HINT2 = "面板透明度.";
	TITAN_TRANS_CONTROL_TOOLTIP = "面板透明度:";
	TITAN_TRANS_CONTROL_TITLE = "透明度";
	TITAN_TRANS_CONTROL_HIGH = "100%";
	TITAN_TRANS_CONTROL_LOW = "0%";
	TITAN_TRANS_MENU_TEXT = "面板透明度";
	
	TITAN_UISCALE_TOOLTIP = "调整界面/面板/字体显示比例";
	TITAN_UISCALE_TOOLTIP_VALUE_UI = "界面比例: ";
	TITAN_UISCALE_TOOLTIP_VALUE_PANEL = "面板比例: ";
	TITAN_UISCALE_TOOLTIP_VALUE_FONT = "字体比例: ";
	TITAN_UISCALE_TOOLTIP_HINT1 = "左键单击调整面板或";
	TITAN_UISCALE_TOOLTIP_HINT2 = "游戏用户界面显示的尺寸大小.";
	TITAN_UISCALE_CONTROL_TOOLTIP_UI = "界面比例: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_PANEL = "面板比例: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_FONT = "字体比例: ";
	TITAN_UISCALE_CONTROL_TITLE_UI = "界面比例";
	TITAN_UISCALE_CONTROL_TITLE_PANEL = "面板比例";
	TITAN_UISCALE_CONTROL_TITLE_FONT = "字体比例";
	TITAN_UISCALE_CONTROL_HIGH_UI = "100%";
	TITAN_UISCALE_CONTROL_HIGH_PANEL = "125%";
	TITAN_UISCALE_CONTROL_HIGH_FONT = "200%";
	TITAN_UISCALE_CONTROL_LOW_UI = "64%";
	TITAN_UISCALE_CONTROL_LOW_PANEL = "75%";
	TITAN_UISCALE_CONTROL_LOW_FONT = "50%";
	TITAN_UISCALE_MENU_TEXT = "界面/面板/字体 比例";
	
	TITAN_VOLUME_TOOLTIP = "调整主音量大小";
	TITAN_VOLUME_TOOLTIP_VALUE = "当前主音量大小: ";
	TITAN_VOLUME_TOOLTIP_HINT1 = "左键单击调整"
	TITAN_VOLUME_TOOLTIP_HINT2 = "主音量大小.";
	TITAN_VOLUME_CONTROL_TOOLTIP = "主音量:";
	TITAN_VOLUME_CONTROL_TITLE = "音量";
	TITAN_VOLUME_CONTROL_HIGH = "高";
	TITAN_VOLUME_CONTROL_LOW = "低";
	TITAN_VOLUME_MENU_TEXT = "音量"

	TITAN_ZONE_SPEED_MENU_TEXT = "地图切换时间";
	TITAN_ZONE_SPEED_LASTZONE = "最后次地图切换时间";
	
	TITAN_XP_FORMAT = "%d";
	TITAN_XP_PERCENT_FORMAT = TITAN_XP_FORMAT.." (%.1f%%)";
	TITAN_XP_BUTTON_LABEL_XPHR_LEVEL = "经验/小时(当前等级): ";
	TITAN_XP_BUTTON_LABEL_XPHR_SESSION = "经验/小时(本次连接): ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_LEVEL = "升级所需时间: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_SESSION = "升级时间:";
	TITAN_XP_TOOLTIP = "经验信息";
	TITAN_XP_TOOLTIP_TOTAL_TIME = "总共游戏时间:";
	TITAN_XP_TOOLTIP_LEVEL_TIME = "当前等级游戏时间:";
	TITAN_XP_TOOLTIP_SESSION_TIME = "本次连接游戏时间:";
	TITAN_XP_TOOLTIP_TOTAL_XP = "当前等级所需经验:";
	TITAN_XP_TOOLTIP_LEVEL_XP = "当前等级已获得经验: ";
	TITAN_XP_TOOLTIP_TOLEVEL_XP = "升级还需经验: ";
	TITAN_XP_TOOLTIP_SESSION_XP = "本次连接获得经验:";
	TITAN_XP_TOOLTIP_XPHR_LEVEL = "经验/小时（当前等级）:";
	TITAN_XP_TOOLTIP_XPHR_SESSION = "经验/小时（本次连接）:";
	TITAN_XP_TOOLTIP_TOLEVEL_LEVEL = "升级时间（按等级效率）:";
	TITAN_XP_TOOLTIP_TOLEVEL_SESSION = "升级时间（按连接效率）:";
	TITAN_XP_MENU_TEXT = "经验信息";
	TITAN_XP_MENU_SHOW_XPHR_THIS_LEVEL = "显示当前等级每小时经验";
	TITAN_XP_MENU_SHOW_XPHR_THIS_SESSION = "显示本次连接每小时经验";
	TITAN_XP_MENU_RESET_SESSION = "重置经验统计";
	
	TITAN_REGEN_MENU_TEXT 		= "恢复"
	TITAN_REGEN_MENU_TOOLTIP_TITLE	= "恢复速度"
	TITAN_REGEN_MENU_SHOW1 		= "显示"
	TITAN_REGEN_MENU_SHOW2 		= "生命"
	TITAN_REGEN_MENU_SHOW3 		= "法力"
	TITAN_REGEN_MENU_SHOW4		= "显示百分比"
	TITAN_REGEN_BUTTON_TEXT_HP 		= "生命: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_HP_PERCENT 	= "生命: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP 		= "法力: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP_PERCENT 	= "法力: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP1 		= "生命: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP2 		= "法力: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP3 		= "最高生命恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP4 		= "最低生命恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP5 		= "最高法力恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP6 		= "最低法力恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP7		= "上次战斗法力恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..GREEN_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE.."%%)";

	TITAN_ITEMBONUSES_TEXT = "装备";
	TITAN_ITEMBONUSES_DISPLAY_NONE = "不显示任何属性";
	TITAN_ITEMBONUSES_SHORTDISPLAY = "显示摘要";
	TITAN_ITEMBONUSES_BONUSSCANNER_MISSING = "需要 BonusScanner 函数库";

	TITAN_ITEMBONUSES_CAT_ATT = "属性";
	TITAN_ITEMBONUSES_CAT_RES = "抗性";
	TITAN_ITEMBONUSES_CAT_SKILL = "技能";
	TITAN_ITEMBONUSES_CAT_BON = "战斗相关属性";
	TITAN_ITEMBONUSES_CAT_SBON = "法术";
	TITAN_ITEMBONUSES_CAT_OBON = "生命和法力";

	TITAN_HONORPLUS_BUTTON_LABEL_RANK = RANK..": ";
	TITAN_HONORPLUS_CLASSINDEX = {
		["德鲁伊"]   = 1,
		["猎人"]  = 2,
		["法师"]    = 3,
		["圣骑士"] = 4,
		["牧师"]  = 5,
		["盗贼"]   = 6,
		["萨满祭司"]  = 7,
		["术士"] = 8,
		["战士"] = 9,
	};
	
	TITAN_HONORPLUS_BUTTON_LABEL_HK = "HK: ";
	TITAN_HONORPLUS_BUTTON_LABEL_DK = "DK: ";
	TITAN_HONORPLUS_TOOLTIP = "PVP 荣誉+ 信息";
	TITAN_HONORPLUS_TOOLTIP_THISWEEK = "本周"
	TITAN_HONORPLUS_MENU_TEXT = "荣誉+";
	TITAN_HONORPLUS_MENU_CALCTODAY = "添加今天的 HK 核算";
	TITAN_HONORPLUS_MENU_SCT = "滚动显示战斗信息";
	TITAN_HONORPLUS_MENU_OPIUM = "Opium Support";
	TITAN_HONORPLUS_MENU_SCOREBOARDCLASSCOLORSYMBOL = "记分牌颜色职业标志";
	TITAN_HONORPLUS_MENU_SCOREBOARDCLASSCOLORLIST = "记分牌颜色职业名称";
	TITAN_HONORPLUS_MENU_SCOREBOARDKILLS = "在计分版上显示今日击杀";
	TITAN_HONORPLUS_MENU_PRINTBONUS = "在聊天窗口显示荣誉得分";
	TITAN_HONORPLUS_MENU_TOOLTIP = "显示提示信息";
	TITAN_HONORPLUS_MENU_SORTBYHONOR = "荣誉类别";
	TITAN_HONORPLUS_MENU_SORTBYKILLS = "击杀类别";
	TITAN_HONORPLUS_ESTIMATED = "%s 死亡， [今天 %d 次。], 军衔: %s。 [实际荣誉获得: %d]";
	TITAN_HONORPLUS_BONUSHONORGAINED = "你获得 %s 荣誉奖励。";
	TITAN_HONORPLUS_BONUS = "奖励";
	TITAN_HONORPLUS_HONORESTIMATED = "荣誉评估";
	TITAN_HONORPLUS_HONORESTIMATION = "荣誉评估";
	TITAN_HONORPLUS_PROGRESS = "提升";
	TITAN_HONORPLUS_TODAYHONOR = "今日荣誉";
	TITAN_HONORPLUS_KILLS = "击杀";
	TITAN_HONORPLUS_DEATHS = "死亡";
	TITAN_HONORPLUS_TOTAL = "合计";
	TITAN_HONORPLUS_TOP15 = "击杀目标等级前15名";
	TITAN_HONORPLUS_PVPSTATS = "PvP 统计";
	TITAN_HONORPLUS_NOKILLS = "无击杀";
	TITAN_HONORPLUS_HINT = "提示: 左键显示不同状态。";
	TITAN_HONORPLUS_HINT_TOOLTIP = "(左键点击更多信息)";
	TITAN_HONORPLUS_TOOLTIP_TODAYSKILLS = "一天内杀死同一玩家.\n超过4次, 将不会再从此玩家身上获得荣誉.";
	TITAN_HONORPLUS_KILLEDTODAY = "今天已击杀";
	TITAN_HONORPLUS_MENU_AUTORELEASE = "自动释放";
	TITAN_HONORPLUS_MENU_AUTOJOINBG = "自动加入战场";
	TITAN_HONORPLUS_MENU_AUTOBGMAP = "自动显示战场地图";
	TITAN_HONORPLUS_AUTOJOINBG = "30秒后自动加入战场...";
	TITAN_HONORPLUS_AUTOJOINBG_CANCEL = "进入战场被取消。";
	TITAN_HONORPLUS_AUTOJOINBG_DONE = "现在进入战场。祝好运!";
	TITAN_HONORPLUS_BONUSHONOR = "been awarded (%d+)% honor points";
	TITAN_HONORPLUS_BGZONES = {"Alterac Valley", "Warsong Gulch", "Arathi Basin"};

	--Titan Repair
	REPAIR_LOCALE = {
		pattern = "^Durability (%d+) / (%d+)$",
		menu = "Durability Info",
		tooltip = "Durability Info",
		button = "Durability: ",
		percentage = "Show as Percentage",
		itemname = "Show Item Name",
		undamaged = "Show undamaged Items",
		nothing = "Nothing damaged",
		confirmation = "Do you want to repair all equipped Items?",
		popup = "Show repair popup",
		repinventory = "Repair Inventory too",
		showinventory = "Calculate Inventory damage"
	};

	TITAN_PLUGINS_MENU_TITLE = "插件";
	
	CUSTOMIZATION_FEATURE_COMING_SOON = "自定义功能开发中...";
end

