---  Variables, don't need translated ---
TITAN_EMOTEMENU_LOC_US = "enUS";
TITAN_EMOTEMENU_LOC_DE = "deDE";
TITAN_EMOTEMENU_LOC_FR = "frFR";
TITAN_EMOTEMENU_SPACER = 42;



	TITAN_EMOTEMENU_MENU_BARTEXT = "表情";
	TITAN_EMOTEMENU_MENU_TEXT = "表情";
	TITAN_EMOTEMENU_MENU_TEXTRIGHT = "表情 (右)";
	
	TITAN_EMOTEMENU_CAT_FRIENDLY = "Friendly Emotes";
	TITAN_EMOTEMENU_CAT_AGGRESSIVE = "Aggressive Emotes";
	TITAN_EMOTEMENU_CAT_NEUTRAL = "Neutral Emotes";
	TITAN_EMOTEMENU_CAT_OTHER = "Other Emotes";
	

